version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      # Database configuration
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: supplier_db
      # Redis configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: supplier_db
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
