-- Suppliers table
CREATE TABLE "suppliers" (
    "supplier_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supplier_name" VARCHAR(255) NOT NULL,
    "contact_info" TEXT NULL,
    "financial_stability_score" DECIMAL(5, 2) NULL,
    "created_at" TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP
);

-- Supplier performance metrics table
CREATE TABLE "supplier_performance_metrics" (
    "supplier_id" INTEGER NOT NULL,
    "date" DATE NOT NULL,
    "cost_of_goods" DECIMAL(10, 2) NULL,
    "length_of_delivery" INTEGER NULL,
    "number_of_late_deliveries" INTEGER NULL,
    "number_of_recalled_products" INTEGER NULL,
    "quality_rating" INTEGER NULL CHECK (quality_rating >= 1 AND quality_rating <= 5),
    "created_at" TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("supplier_id", "date"),
    FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id")
);

-- Suppliers to evaluate table
CREATE TABLE "suppliers_to_evaluate" (
    "recommendation_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supplier_1" INTEGER NOT NULL,
    "supplier_2" INTEGER NOT NULL,
    FOREIGN KEY ("supplier_1") REFERENCES "suppliers" ("supplier_id"),
    FOREIGN KEY ("supplier_2") REFERENCES "suppliers" ("supplier_id")
);

-- Actions generated by Connie table
CREATE TABLE "actions_generated_by_connie" (
    "action_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "recommendation_id" INTEGER NULL,
    "supplier_id" INTEGER NULL,
    "date" DATE NULL,
    "action_type" VARCHAR(255) NOT NULL,
    "description" TEXT NULL,
    "status" VARCHAR(50) NULL DEFAULT 'pending',
    "created_at" TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("recommendation_id") REFERENCES "suppliers_to_evaluate" ("recommendation_id"),
    FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id")
);

-- Emails table
CREATE TABLE "emails" (
    "email_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "action_id" INTEGER NOT NULL,
    "to_address" VARCHAR(255) NOT NULL,
    "from_address" VARCHAR(255) NOT NULL,
    "subject" VARCHAR(255) NOT NULL,
    "body" TEXT NOT NULL,
    "date_created" TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    "date_sent" TIMESTAMP WITHOUT TIME ZONE NULL,
    FOREIGN KEY ("action_id") REFERENCES "actions_generated_by_connie" ("action_id")
);

-- Suppliers data
INSERT INTO "suppliers" (
    "supplier_id", "supplier_name", "contact_info", "financial_stability_score"
) VALUES
      (1, 'Alpha Supplies', 'contact@alphasupplies.com', 85.5),
      (2, 'Beta Traders', 'info@betatraders.com', 78.0),
      (3, 'Gamma Industries', 'sales@gammaindustries.com', 90.0);